name: Truawake
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you plan to publish

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  video_player: ^2.8.2
  intl: ^0.20.2
  local_auth: ^2.3.0
  just_audio: ^0.10.2
  camera: ^0.11.1
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  provider: ^6.1.0
  shared_preferences: ^2.2.3
  geolocator: ^14.0.0
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  http: ^1.2.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^7.1.1
  firebase_storage: ^13.0.1
  fl_chart: ^1.1.1
  flutter_secure_storage: ^9.2.4
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.3
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # UI Icons
    - assets/logo.png
    - assets/myprofile_icon.png
    - assets/appsettings_icon.webp
    - assets/myvehicle_icon.png
    - assets/verifylicence_icon.webp
    - assets/setalarm_icon.png
    - assets/checkweather_icon.png
    - assets/setlocation_icon.png
    - assets/myactivity_icon.png
    - assets/driver_icon.png
    - assets/map_icon.png
    - assets/history_icon.png

    # Notification/Alarm Sound Files
    - assets/soft_alarm.ogg
    - assets/sound_of_the_sea.ogg
    - assets/squirrel.ogg
    - assets/stepping_stone.ogg
    - assets/dolphin.ogg
    - assets/argon.ogg
    - assets/caron.ogg
    - assets/helium.ogg
    - assets/krypton.ogg
    - assets/neon.ogg
    - assets/osmium.ogg
    - assets/oxygen.ogg
    - assets/platinum.ogg
    - assets/timer.ogg
    - assets/bedside.ogg
    - assets/coil.ogg
    - assets/frogs.ogg
    - assets/incoming.ogg
    - assets/kashio.ogg


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/App_icon/icon.png"
