// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJlG6wGXh1BzJQOTKE94tHNnLj7_8ykQ',
    appId: '1:901869801160:web:f5bdaea65134131ca45ffd',
    messagingSenderId: '901869801160',
    projectId: 'truawake-fc914',
    authDomain: 'truawake-fc914.firebaseapp.com',
    storageBucket: 'truawake-fc914.firebasestorage.app',
    measurementId: 'G-FX5K6EXY8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJak924sfD5bzi4GZW-rWCEtI9CAm0n34',
    appId: '1:901869801160:android:d6ed125b31730bc2a45ffd',
    messagingSenderId: '901869801160',
    projectId: 'truawake-fc914',
    storageBucket: 'truawake-fc914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiMbQCma6l7tB6PmjnE_RtiqvjyW4JVqc',
    appId: '1:901869801160:ios:6c9903b3e2f1dd8da45ffd',
    messagingSenderId: '901869801160',
    projectId: 'truawake-fc914',
    storageBucket: 'truawake-fc914.firebasestorage.app',
    iosBundleId: 'com.example.fypTruawake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiMbQCma6l7tB6PmjnE_RtiqvjyW4JVqc',
    appId: '1:901869801160:ios:6c9903b3e2f1dd8da45ffd',
    messagingSenderId: '901869801160',
    projectId: 'truawake-fc914',
    storageBucket: 'truawake-fc914.firebasestorage.app',
    iosBundleId: 'com.example.fypTruawake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrJlG6wGXh1BzJQOTKE94tHNnLj7_8ykQ',
    appId: '1:901869801160:web:dd84a79b181355b4a45ffd',
    messagingSenderId: '901869801160',
    projectId: 'truawake-fc914',
    authDomain: 'truawake-fc914.firebaseapp.com',
    storageBucket: 'truawake-fc914.firebasestorage.app',
    measurementId: 'G-XNXE2JKGG9',
  );
}
